- name: restart postgres
  systemd:
    name: postgresql
    state: restarted

- name: start postgres
  systemd:
    name: postgresql
    state: started

- name: stop postgres
  systemd:
    name: postgresql
    state: stopped

- name: enable postgres
  systemd:
    name: postgresql
    enabled: yes